name        "deploy"
description "Deploy applications"
maintainer  "Studio Arcana co.,Ltd."
license     "Apache 2.0"
version     "1.0.0"

depends "dependencies"
depends "scm_helper"
depends "apache2"
depends "ssh_users"
depends "opsworks_agent_monit"
depends "php"
depends "mysql"
depends "golang"
depends "lsyncd"
depends "git_ssh_wrapper"
depends "composer"
depends "nfs"

recipe "deploy::php-deploy", "Deploy a PHP application"
recipe "deploy::basercms", "Basic Configuration for BaserCMS"
recipe "deploy::cms", "Plugin Configuration for BaserCMS"
recipe "deploy::sync", "Synchronism Configuration"
recipe "deploy::phpmyadmin", "Deploy a phpMyAdmin application"
recipe "deploy::nfs_setup", "Deploy a NFS application"
