---
provisioner:
  name: chef_solo
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: debian-7.7
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: centos-6.5
- name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[lsyncd_test::integration]
    attributes: {
      "lsyncd": {
        "interval": 1
      }
    }
